# Change these first
owner: govindbhardwaj # Your GitHub organization or username, where this repository lives
repo: monitor-ritam # The name of this repository

sites:
  - name: Mobile Application APIs
    url: https://ritamdigital.org
  - name: Editor CMS
    url: https://editor.ritamdigital.org
  - name: Crawler APIs
    url: https://crawler.ritamdigital.org
  - name: Jenkins Server
    url: https://jenkins.ritamdigital.org

status-website:
  baseUrl: /monitor-ritam
  name: RitamDigital Uptime Monitoring
  logoUrl: https://www.ritamdigital.org/content/8b4e383b880a8e026f4ea3fd339893f3.png
  introTitle: "Ritam websites uptime monitoring powered by **Upptime**"
  introMessage: This is Ritam Digital uptime monitoring website. Please check individual statuses for websites listed below.
  navbar:
    - title: Mobile APIs
      href: https://ritamdigital.org
    - title: Editor CMS
      href: https://editor.ritamdigital.org
    - title: Crawler APIs
      href: https://crawler.ritamdigital.org
    - title: Jenkins
      href: https://jenkins.ritamdigital.org
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
